# Generated by Django 5.0.1 on 2024-02-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Email_Address', models.CharField(max_length=100)),
                ('Mobile_Number', models.IntegerField()),
                ('Local_Address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblcustomer',
                'ordering': ('Customer_Name',),
            },
        ),
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Weight', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Igst', models.IntegerField()),
                ('Cgst', models.IntegerField()),
            ],
            options={
                'db_table': 'tblproduct',
                'ordering': ('Product_name',),
            },
        ),
        migrations.CreateModel(
            name='Invoicemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_Date', models.DateField()),
                ('Total_Amount', models.IntegerField()),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to='InvoiceApp.customermodel')),
            ],
            options={
                'db_table': 'tblinvoice',
                'ordering': ('Total_Amount',),
            },
        ),
        migrations.CreateModel(
            name='Paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Date', models.DateField()),
                ('Payment_Amount', models.IntegerField()),
                ('Payment_mode', models.CharField(max_length=100)),
                ('Payment_description', models.CharField(max_length=100)),
                ('Total_Amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='InvoiceApp.invoicemodel')),
            ],
            options={
                'db_table': 'tblpayment',
                'ordering': ('Payment_Date',),
            },
        ),
        migrations.CreateModel(
            name='Invoiceproductmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('GST', models.IntegerField()),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='InvoiceApp.customermodel')),
                ('Total_Amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='InvoiceApp.invoicemodel')),
                ('Payment_Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='InvoiceApp.paymentmodel')),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='InvoiceApp.productmodel')),
            ],
            options={
                'db_table': 'tblinvoiceproduct',
                'ordering': ('Quantity',),
            },
        ),
    ]
