# Generated by Django 5.0.1 on 2024-02-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Invoice_Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='Payment_Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='Total_Amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='InvoiceApp.invoicemodel'),
        ),
    ]
