# Generated by Django 5.0.1 on 2024-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0002_alter_invoicemodel_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Total_Amount',
            field=models.FloatField(),
        ),
    ]
