# Generated by Django 5.0.1 on 2024-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0003_alter_invoicemodel_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Total_Amount',
            field=models.CharField(max_length=100),
        ),
    ]
